services:
    _defaults:
        autowire: true

    Demontpx\RigidSearchBundle\Search\SearchManager:
    Demontpx\RigidSearchBundle\Search\ItemSearchManagerFactory:

    Demontpx\RigidSearchBundle\Search\Index\IndexInterface: '@Demontpx\RigidSearchBundle\Search\Index\OrmIndex'
    Demontpx\RigidSearchBundle\Search\Index\OrmIndex:

    Demontpx\RigidSearchBundle\Search\Processor\NormalizeRouteProcessor:
        tags: [demontpx_rigid_search.document_processor]

    Demontpx\RigidSearchBundle\Search\OpenSearchDescriptionProvider:

    Demontpx\RigidSearchBundle\Pagination\SearchQueryPaginationSubscriber:
        tags: [knp_paginator.subscriber]

    Demontpx\RigidSearchBundle\Repository\DocumentRepository:
    Demontpx\RigidSearchBundle\Repository\FieldRepository:

    Demontpx\RigidSearchBundle\Command\:
        resource: '../../Command'
        autowire: true
        tags: [console.command]

    Demontpx\RigidSearchBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        tags: [controller.service_arguments]
